# Generated by Django 6.0.5 on 2026-05-29 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-confidence_score', '-last_accessed']},
        ),
        migrations.AddField(
            model_name='memory',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='memory',
            name='context_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='memory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('episodic', 'Episodic'), ('semantic', 'Semantic'), ('procedural', 'Procedural'), ('temporal', 'Temporal')], default='semantic', max_length=20),
        ),
        migrations.CreateModel(
            name='AutonomousDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('decision_made', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=0.0)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('rejected', 'Rejected by user')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=50)),
                ('cron_schedule', models.CharField(max_length=100)),
                ('action', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
