# Generated by Django 6.0.5 on 2026-07-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_status',
            field=models.CharField(choices=[('ok', 'Ok'), ('error', 'Error'), ('never', 'Never run')], default='never', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(default='chat', max_length=50),
        ),
    ]
