# Generated by Django 6.0.5 on 2026-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_notified',
            field=models.BooleanField(default=False),
        ),
    ]
