# Generated by Django 6.0.5 on 2026-07-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_task_deadline_notified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
