# Generated by Django 6.0.5 on 2026-09-18 18:12

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_delete_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='ASH_SELF.md', max_length=255)),
                ('heading', models.CharField(max_length=500)),
                ('ordinal', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'ordinal'],
                'unique_together': {('source', 'ordinal')},
            },
        ),
    ]
